[package]
name = "hacksimulators"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "cpu"
path = "src/cpu/main.rs"

[[bin]]
name = "vm"
path = "src/vm/main.rs"

[[simulator]]
name = "simulator"
path = "src/simulator/main.rs"

[dependencies]
